### ISSUE TITLE
Missing announcer

### ISSUE THREAD

**Issue by GGrev** [thomas-barthelemy/QQ-LoL-Localizer#10]
Everything works like a charm, except of the announcing voice. I can see the inscription of the seconds countdown before mob spawn and when making double, triple etc kills, however the voice is missing. I tried reinstalling and it didn`t help. Is there a possible way to fix it, or somehow bypass the issue? It is not a crucial problem, but it adds so much thrill to the game.
Thank you very much for this nice program which saved people so much time!

**Comment by thomas-barthelemy** [comment]
Thanks for the feedback, released v2.11 with what worked for me, give it a try!
On a side note it gives you the original Chinese sounds, as the US sounds aren't included in the client at all.

**Comment by GGrev** [comment]
It works now! Thank you VERY much!

**Comment by thomas-barthelemy** [comment]
@GGrev I've had partial feedback on another issue related to player's name in Chinese not showing properly, is that working fine for you? Have you noticed any other issue?

**Comment by GGrev** [comment]
@thomas-barthelemy I had squares instead of the Chinese players names in 2.10. Will check 2.11 again a bit later and text you back. Haven`t noticed any other issues except of the missing rookie bonus pop ups, but i claimed them from the lol/qq/gifts link.

**Comment by thomas-barthelemy** [comment]
ok, the name issue will be tracked with #9 so this specific issue can be closed.
