### ISSUE TITLE
QQ LoL Localizer says fixed but everything is still Chinese

### ISSUE THREAD

**Issue by neatocleoyeah** [thomas-barthelemy/QQ-LoL-Localizer#13]
Pretty much title says everything. Successfully installed LoL. Ran the localizer, reopened LoL and everything is still in Chinese. Made sure everything was updated, tried again, restarted computer, but no luck. Localizer says it is Fixed though. New client issues?

**Comment by Camineet** [comment]
same problem here a 30 days back until i ran as admin

**Comment by neatocleoyeah** [comment]
That did the trick! Thank you!

**Comment by Camineet** [comment]
np pal

my ign Camineet btw xD

**Comment by thomas-barthelemy** [comment]
See #16
