### ISSUE TITLE
no exe file? swear im not retarded

### ISSUE THREAD

**Issue by truckbus** [thomas-barthelemy/QQ-LoL-Localizer#15]
hey - maybe i am retarded but for the life of me i cannot find the exe file. 

downloaded qq-lol-localizer-2.14zip (also tried the master version)
unzipped
nothing to run...

please help (also lol username is datboi ) hmu

https://gyazo.com/b5da1caaf53bc765b0bb902223f86fd4
https://gyazo.com/587bbf1a47361523ea07e3f8895b50f8

**Comment by timchez** [comment]
Might be the antivirus which instantly deleted exe file taking it as a threat. Just sayin..
