### ISSUE TITLE
Chat Text Not translated/ CFG/Locale.cfq missing

### ISSUE THREAD

**Issue by nofacenoname** [thomas-barthelemy/QQ-LoL-Localizer#17]
Hello Thomas, 

Hope you are well! 

After a fresh install on a new computer I'm unable to get the chat translated.
![capture](https://user-images.githubusercontent.com/28862249/28485837-f7b48b1c-6eae-11e7-9fdf-7ae8eb0330e2.JPG)
![capture2](https://user-images.githubusercontent.com/28862249/28485839-f868ff5c-6eae-11e7-8f90-9ecc483a62b7.JPG)

I will not appologize for my Gamertag, it is glorious. :-P 

Cheers, 
NFNF

**Comment by Deadly78** [comment]
Right click locale.cfg and open file location. Then go into the file "default" and find locale.cfg. Then copy it and paste it outside with default. Then just run the application and fix all.

**Comment by nofacenoname** [comment]
That worked. Thanks!
