### ISSUE TITLE
Client crashing on latest version

### ISSUE THREAD

**Issue by drunkendori** [thomas-barthelemy/QQ-LoL-Localizer#2]
I've been using the one click localizer since I discovered it and loved it but recently it always crashes the game and I'm forced to play the game in chinese. I downloaded the new version here but I have no idea how to apply it to the game. 

The instructions said;

    Launch the TCLS client to be sure your version is up-to-date.
    Open the QQ LoL Localizer.
    If it's the first time you use it, you will have to define where is located your "TCLS\Client.exe".
    You should have a view of all files that need to be modified and there current state. A file marked as "Fixed" doesn't require any operation, else it needs to be fixed. To fix you can either select the file(s) you want and click on "Fix Selected" or just click on "Fix All".
    After an update, you might need to re-fix some of the files.

My question is where is the application? Or are these instructions invalid already? 

Any help is greatly appreciated.

**Comment by drunkendori** [comment]
Do I open it with Visual Studio?

**Comment by thomas-barthelemy** [comment]
The binary is found in the release section:
https://github.com/thomas-barthelemy/QQ-LoL-Localizer/releases

**Comment by drunkendori** [comment]
I see. Well its the community's loss =( 

So how do I use this version of the localizer? 

Anyway all the best to you wherever you are.

**Comment by thomas-barthelemy** [comment]
All you would have to do is to download the latest release:
https://github.com/thomas-barthelemy/QQ-LoL-Localizer/releases/download/v2.8/QQ.LoL.Localizer.v2.8.zip

extract it and run the .exe file. nothing too crazy =)

I will try to get an up-to-date version of the QQ LoL client sometime this week see if I can figure out the problem.

**Comment by drunkendori** [comment]
Just ran the exe game still crashes. How do I revert it back to the original state?

**Comment by thomas-barthelemy** [comment]
Technically if you go into the option and check the `advanced` check-box you should have access to revert all functions.

What the app does is it creates a backup of the files it modifies so it should be just fine for reverting.

**Comment by drunkendori** [comment]
wow that was fast! Thanks!

**Comment by drunkendori** [comment]
Ahh I needed to turn on advanced view to be able to see it.

**Comment by thomas-barthelemy** [comment]
Solved in v2.9 (5fbd4aa), see release section.

**Comment by drunkendori** [comment]
Ill test it when I get home. cheers!

**Comment by drunkendori** [comment]
Works perfectly now. Thanks for the hard work!
