### ISSUE TITLE
Make a distribute/bin folder?

### ISSUE THREAD

**Issue by jamessimo** [thomas-barthelemy/QQ-LoL-Localizer#3]
Could you add a compiled version of the app into the repo? As I feel most players don't have a visual studio on hand to compile it each time.

Cheers

**Comment by thomas-barthelemy** [comment]
Binaries are available in the release section:
https://github.com/thomas-barthelemy/QQ-LoL-Localizer/releases

I'll edit the Readme to ensure other people do not miss it either.
