### ISSUE TITLE
Season 6

### ISSUE THREAD

**Issue by drunkendori** [thomas-barthelemy/QQ-LoL-Localizer#4]
Cant seem to be used in season 6

**Comment by thomas-barthelemy** [comment]
Too many updates! So where is the issue right now? within the Air client or the Game client? What's happening (or not happening)?

**Comment by drunkendori** [comment]
The problem seems to be the addition of new items the files do not corrospond. This is just my guess. Tried loading and it crashed.

**Comment by thomas-barthelemy** [comment]
I checked today on the latest version (3.1.6.9) and it worked correctly for me to start the Air client and start a custom game.
Be sure you have the latest localizer version (2.9.0.0) and that all files are correctly fixed.

If that is still an issue then be more specific on how to reproduce this bug?

**Comment by thomas-barthelemy** [comment]
I'm gonna close that as I'm not able to reproduce it. Works just fine for me. Feel free to re-open it if you have a more reproducible scenario for me to test.

**Comment by jamessimo** [comment]
I can confirm that every thing is working for Win7, Win 8.1 and Winserver 2012R2.

**Comment by thomas-barthelemy** [comment]
Kudos for actually testing LoL on a Win. Server <3
