### ISSUE TITLE
Another not an issue...

### ISSUE THREAD

**Issue by MasterDevil90** [thomas-barthelemy/QQ-LoL-Localizer#6]
Hello, 
I was wondering about the possibility to reuse this on the regular client to localize the game in Arabic
i just need to test this first on the in-game client before i give it a try at the air-client, i tried to look for the files using RAF manger and RAF tools but no use. 
and are fonts  needed for this ? since arabic displays as squares when typing in game, and not correctly when using the air client. 
sorry, if that is absolutely a yes i'm a cs student and i'm just trying to make sense of the code for now and i need just some guidance on that.

**Comment by thomas-barthelemy** [comment]
What you are trying to do is a bit different as it's trying to create a new locale entirely.
This app uses leftover of the EN locale and tries to replace the ZH local using those.

In that case your first step should not be to get confused with .NET code but to try to make it work manually.
You can have a look at the QQFileModels folder which contains an implementation for each file that is locale dependent and 'fixable' using existing info.

Anything AIR related won't be in game as you mentioned so yeah probably not the first thing to look at.
For the in-game, the audio would be a pain, and I guess it's not your goal either.

For what remains you gonna have 2 main things:
- The font related files, as the default font won't support UTF-8 character you will have in Arabic (same issue I had with Chinese) so will have to change to a font that works for those characters.
- The actual translation (hero/item/misc) which is a big key/value file, easy to modify. I don't have an install around but could be this: `game\data\CFG\locale.cfg`

**Comment by thomas-barthelemy** [comment]
The latest patch of the game seem to include many languages but no Arabic sadly. You can check the list of local binary here: Datas2.zip\DATA\FINAL\Localized\
to open a .wad.client you can extract it, you will get the .wad. you can open the .wad with a text editor.
There you can translate it manually!
