### ISSUE TITLE
Player name in chinese seen as boxes

### ISSUE THREAD

**Issue by drunkendori** [thomas-barthelemy/QQ-LoL-Localizer#9]
Player names are seen as boxes during loading screen and in game. 
Cant seem to up load screenshots tho. Its stuck at Uploading your files for quite awhile.

**Comment by thomas-barthelemy** [comment]
tried the latest v2.10 version of the localizer?
https://github.com/thomas-barthelemy/QQ-LoL-Localizer/releases/tag/v2.10

**Comment by drunkendori** [comment]
Previous version didn't work anymore so I downloaded the latest version and tried yesterday. All the fonts seems smaller and Chinese names do not appear. Do you want me to send you screenshots? Can't seem to post them here.

**Comment by thomas-barthelemy** [comment]
I tried on a brand new fresh install and I didn't see any problem, although #7 seems to be fairly similar issue which is the reason why v2.10 was released and users confirmed it was working correctly with this version.

Do you mind checking with a fresh install see how it goes?

**Comment by drunkendori** [comment]
I'll do that

**Comment by GGrev** [comment]
The latest version (2.11) also has this issue in my case.

**Comment by drunkendori** [comment]
just updated to 2.11. Names still appear as boxes during loading screen and in game on a fresh install.

**Comment by Dominic-LIN** [comment]
Hi. i got the same issue for the 2.11 version, i.e. Chinese player name shown as small boxes during loading and in game; whereas other Chinese characters can be seen, e.g. the characters in the conversation box.

**Comment by thomas-barthelemy** [comment]
I as I am not currently in China and don't play anymore I usually test by creating custom games which doesn't show those issues. I will try to find way to reproduce that in order to debug it. Thanks for all the feedback

**Comment by thomas-barthelemy** [comment]
I haven't been able to fully test that build yet as I'm just getting time-out from the server right now,
but consider giving a test to the v.2.13 pre-release version and let me know how it goes! Hopefully that should fix this issue.

**Comment by thomas-barthelemy** [comment]
I was able to test it this morning and made some more changes, the 2.14 stable build should fix both issues mentioned here related to font!
